#Konfigurime te log
logging:
  level:
    root: INFO
  file:
    name: /logs/log-generated.log
    max-size: 10MB
    append: true
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"