apiVersion: v1
kind: Service
metadata:
  name: backend-svc1
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc2
spec:
  type: NodePort
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8080
      nodePort: 30813
  selector:
    app: backend

# kubectl apply -f app-service.yaml